### PR TITLE
depricate gitlab ci from docker workshop

### PR DESCRIPTION
**Pull request by vlukashenko**
As was discussed on Monday HSF training meeting we remove for a time being gitlab-CI related lessons.
The corresponding pages are now moved to the Friday "challenges" during the mentor sessions.

### CODE REVIEW

**Review by michmx — CHANGES_REQUESTED** [review]
@vlukashenko  Now that I am thinking... is there any way to instead of deleting the chapters, we can hide them for now? In that way, we will not lose the git history of the files. Also, at some point we can bring them back as extras.

**Comment by vlukashenko** [comment]
> @vlukashenko Now that I am thinking... is there any way to instead of deleting the chapters, we can hide them for now? In that way, we will not lose the git history of the files. Also, at some point we can bring them back as extras.

I also thought of this. I know that pages are generated automatically by looping over the content of the `_episodes`. What I think can be done - is looping over the set range. Let me try

**Review by michmx — APPROVED** [review]

**Comment by michmx** [comment]
@all-contributors please add @vlukashenko as maintainer

**Comment by michmx** [comment]
@all-contributors please add @vlukashenko for maintenance

**Comment by michmx** [comment]
@all-contributors please add @vlukashenko for content

**Pull request merged**
