### PR TITLE
add glossary

### LINKED ISSUE #25: Add Glossary
Here: https://hsf-training.github.io/hsf-training-docker/reference.html

### PR DESCRIPTION
**Pull request by amanmdesai**
Closes #25 

Includes only the major steps required to install a docker image, run it and exit from the image:

### CODE REVIEW

**Comment by klieret** [comment]
I don't think this is a glossary though. This is more like a cheatsheet. Ideally the "cheat sheet" part should be generated automatically from the keypoints that are added below every lessons, see for example here: https://swcarpentry.github.io/shell-novice/reference.html

I think it would be good to instead update the keypoints so that they are really meaningful like that

**Comment by amanmdesai** [comment]
Right this is isnt glossary but cheat-sheet (I should have changed the title). What I am thinking is that we have a cheat sheet -kind of thing  at the end so that all the main commands can be found on one page with easy access. (I think the heading should be "summary of frequently used commands").


We can also update the keypoints as you suggest to include that.

**Comment by amanmdesai** [comment]
i have opened a new issue #48

**Comment by klieret** [comment]
Thanks again for working on this. I think with the keypoints soon updated by your other PR, we should close this one. Because the keypoints will already create a very similar cheat sheet. Sorry about this!

**Pull request closed without merging**
