### PR TITLE
fix docker logo

### LINKED ISSUE #44: docker logo is missing
<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this issue is about a specific episode within a lesson, please provide its link or filename.

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to respond to your contribution.
To ensure that the right people get notified, you can tag some of the last contributors with `@githubname`.

Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum. If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact the HSF training convenors ([contacts here](https://hepsoftwarefoundation.org/workinggroups/training.html)).

You may delete these instructions from your issue.

\- HSF Training
</details>

### PR DESCRIPTION
**Pull request by amanmdesai**
Closes #44

### CODE REVIEW

**Comment by klieret** [comment]
Maybe it's best to simply copy the logo over so it doesn't break again?

**Comment by amanmdesai** [comment]
> Maybe it's best to simply copy the logo over so it doesn't break again?

yeah will try that. (for some reason the docker logo image fails to render whereas if i try other image, they do render)

will fix this

**Comment by amanmdesai** [comment]
issue was with the image format

**Review by klieret — APPROVED** [review]
Thanks!

**Pull request merged**
